version: '3.8'
services:
  WhiteBrook-api:
    image: whitebrook-dev/whitebrook-api:latest
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_Kestrel__Certificates__Default__Password}